<?php
if (!defined('ABSPATH')) {
    exit;
}

$oxitype = sanitize_text_field($_GET['oxitype']);
$oxiimpport = '';
if (!empty($_GET['oxiimpport'])) {
    $oxiimpport = sanitize_text_field($_GET['oxiimpport']);
}

oxi_addons_user_capabilities();
OxiDataAdminImport($oxitype);
global $wpdb;
$table_name = $wpdb->prefix . 'oxi_div_style';
$table_import = $wpdb->prefix . 'oxi_div_import';
$importstyle = $wpdb->get_results("SELECT * FROM $table_import WHERE type = '$oxitype' ORDER BY id DESC", ARRAY_A);
$freeimport = array('style-1', 'style-2','style-3','style-4','style-5','style-6','style-7','style-8');
if (count($importstyle) < 1) {
    foreach ($freeimport as $value) {
        $wpdb->query($wpdb->prepare("INSERT INTO {$table_import} (type, name) VALUES (%s, %s )", array($oxitype, $value)));
    }
    $js = 'location.reload();';
    wp_add_inline_script('oxi-addons-vendor', $js);
}
$file = Array(
    'Style 1OXIIMPORTsocial_iconsOXIIMPORTstyle-1OXIIMPORToxi-addons-preview-BG ||OxiADDSIC-Item |oxi-addons-lg-col-5|oxi-addons-md-col-4|oxi-addons-xs-col-3|oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'Style 2OXIIMPORTsocial_iconsOXIIMPORTstyle-2OXIIMPORToxi-addons-preview-BG ||OxiADDSIC-Item |oxi-addons-lg-col-5|oxi-addons-md-col-4|oxi-addons-xs-col-3|oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'Style 3OXIIMPORTsocial_iconsOXIIMPORTstyle-3OXIIMPORToxi-addons-preview-BG ||OxiADDSIC-Item |oxi-addons-lg-col-5|oxi-addons-md-col-4|oxi-addons-xs-col-3|oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'Style 4OXIIMPORTsocial_iconsOXIIMPORTstyle-4OXIIMPORToxi-addons-preview-BG ||OxiADDSIC-Item |oxi-addons-lg-col-5|oxi-addons-md-col-4|oxi-addons-xs-col-3|oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'style 5OXIIMPORTsocial_iconsOXIIMPORTstyle-5OXIIMPORToxi-addons-preview-BG ||OxiADDSIC-Item |oxi-addons-lg-col-5|oxi-addons-md-col-4|oxi-addons-xs-col-3|oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'style 6OXIIMPORTsocial_iconsOXIIMPORTstyle-6OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |0|0|0|OxiADDSIC-margin-bottom |0|0|0|OxiADDSIC-margin-left |0|0|0|OxiADDSIC-margin-right |0|0|0|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#390075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#007fc9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'style 7OXIIMPORTsocial_iconsOXIIMPORTstyle-7OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#670075| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#c98900| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'style 8OXIIMPORTsocial_iconsOXIIMPORTstyle-8OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |35|35|35| OxiADDSIC-color-view || OxiADDSIC-color |#8700b0| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#0068c9| OxiADDSIC-link-opening |_blank|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||||#|| ||#||##OXIDATA##',
    'style 9OXIIMPORTsocial_iconsOXIIMPORTstyle-9OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#7700c7| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(255,255,255,0.00)|OxiADDSIC-border|2|2|2|OxiADDSIC-border |solid|#7700c7||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(92,92,92,1.00)|OxiADDSIC-H-border|2|2|2|OxiADDSIC-H-border |solid|#5c5c5c||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59,89,153,1.00)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85,172,238,1.00)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221,75,57,1.00)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205,32,31,1.00)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189,8,28,1.00)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##',
    'Style 10OXIIMPORTsocial_iconsOXIIMPORTstyle-10OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#ffffff| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(119,0,199,1.00)|||||||||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(92, 92, 92, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#9100bd||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(189,8,28,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(205,32,31,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(221,75,57,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(85,172,238,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(59,89,153,1.00)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(255,255,255,1.00)||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##',
    'style 11OXIIMPORTsocial_iconsOXIIMPORTstyle-11OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#ffffff| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(183, 0, 189, 1)|||||||||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(92, 92, 92, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#5c5c5c||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##',
    'style 12OXIIMPORTsocial_iconsOXIIMPORTstyle-12OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#ffffff| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(183, 0, 189, 1)|||||||||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(92, 92, 92, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#5c5c5c||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||||#||||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##',
    'style 13OXIIMPORTsocial_iconsOXIIMPORTstyle-13OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |60|60|60|||OxiADDSIC-margin-top |5|5|5|OxiADDSIC-margin-bottom |5|5|5|OxiADDSIC-margin-left |5|5|5|OxiADDSIC-margin-right |5|5|5|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#ffffff| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#5c5c5c| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(101, 0, 189, 1)|||||||||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view || OxiADDSIC-H-bgcolor ||OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#5c5c5c||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||OxiADDSIC-SP-icon-bgcolor||#||#55acee||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||OxiADDSIC-SP-icon-bgcolor||#||#dd4b39||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||OxiADDSIC-SP-icon-bgcolor||#||#cd201f||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||OxiADDSIC-SP-icon-bgcolor||#||#bd081c||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##',
    'style 14OXIIMPORTsocial_iconsOXIIMPORTstyle-14OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#ffffff| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#5c5c5c| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor |rgba(101, 0, 189, 1)|||||||||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view || OxiADDSIC-H-bgcolor ||OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#5c5c5c||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#3b5999||#||OxiADDSIC-SP-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#3b5999||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#55acee||#||OxiADDSIC-SP-icon-bgcolor||#||#55acee||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#55acee||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#dd4b39||#||OxiADDSIC-SP-icon-bgcolor||#||#dd4b39||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#dd4b39||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#cd201f||#||OxiADDSIC-SP-icon-bgcolor||#||#cd201f||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#cd201f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#ffffff||#||OxiADDSIC-SP-H-icon-color||#||#bd081c||#||OxiADDSIC-SP-icon-bgcolor||#||#bd081c||#||OxiADDSIC-SP-H-icon-bgcolor||#||||#||OxiADDSIC-SP-border-color||#||||#||OxiADDSIC-SP-H-border-color||#||#bd081c||#||||#|| ||#||##OXIDATA##',
    'style 15OXIIMPORTsocial_iconsOXIIMPORTstyle-15OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| OxiADDSIC-bgcolor-view || OxiADDSIC-bgcolor ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |dotted|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|||||||||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view ||||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##',
    'style 16OXIIMPORTsocial_iconsOXIIMPORTstyle-16OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| || ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |dotted|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|OxiADDSIC-H-border|0|0|0|OxiADDSIC-H-border |dotted|#ffffff||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||OxiADDSIC-SP-icon-bgcolor||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||||#||||#|| ||#||##OXIDATA##',
    'style 17OXIIMPORTsocial_iconsOXIIMPORTstyle-17OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| || ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |solid|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#da85ff||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||#6191fa||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#9ed0f7||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#ff988a||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#ff918f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#ff9ca6||#||||#|| ||#||##OXIDATA##',
    'style 18OXIIMPORTsocial_iconsOXIIMPORTstyle-18OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| || ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |solid|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#da85ff||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||#6191fa||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#9ed0f7||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#ff988a||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#ff918f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#ff9ca6||#||||#|| ||#||##OXIDATA##',
    'style 19OXIIMPORTsocial_iconsOXIIMPORTstyle-19OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| || ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |solid|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#da85ff||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||#6191fa||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#9ed0f7||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#ff988a||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#ff918f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#ff9ca6||#||||#|| ||#||##OXIDATA##',
    'style 20OXIIMPORTsocial_iconsOXIIMPORTstyle-20OXIIMPORToxi-addons-preview-BG ||||||oxi_addons-icon-width |50|50|50|||OxiADDSIC-margin-top |8|8|8|OxiADDSIC-margin-bottom |8|8|8|OxiADDSIC-margin-left |8|8|8|OxiADDSIC-margin-right |8|8|8|OxiADDSIC-animation||2|0//|OxiADDSIC-size |25|25|25| OxiADDSIC-color-view || OxiADDSIC-color |#8500c2| OxiADDSIC-H-color-view |common| OxiADDSIC-H-color |#ffffff| OxiADDSIC-link-opening |_blank| || ||OxiADDSIC-border|3|3|3|OxiADDSIC-border |solid|#8500c2||OxiADDSIC-radius|80|80|80| OxiADDSIC-H-bgcolor-view |common| OxiADDSIC-H-bgcolor |rgba(133, 0, 194, 1)|OxiADDSIC-H-border|3|3|3|OxiADDSIC-H-border |solid|#da85ff||OxiADDSIC-H-radius|80|80|80| OxiADDSIC-border-view || OxiADDSIC-H-border-view |common|||#|| ||#|||##OXISTYLE##OxiADDSIC-Icon-Class||#||fab fa-facebook-f||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#3b5999||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(59, 89, 153, 1)||#||OxiADDSIC-SP-border-color||#||#3b5999||#||OxiADDSIC-SP-H-border-color||#||#6191fa||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-twitter||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#55acee||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(85, 172, 238, 1)||#||OxiADDSIC-SP-border-color||#||#55acee||#||OxiADDSIC-SP-H-border-color||#||#9ed0f7||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-google-plus-g||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#dd4b39||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(221, 75, 57, 1)||#||OxiADDSIC-SP-border-color||#||#dd4b39||#||OxiADDSIC-SP-H-border-color||#||#ff988a||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-youtube||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#cd201f||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(205, 32, 31, 1)||#||OxiADDSIC-SP-border-color||#||#cd201f||#||OxiADDSIC-SP-H-border-color||#||#ff918f||#||||#|| ||#||##OXIDATA##OxiADDSIC-Icon-Class||#||fab fa-pinterest||#||OxiADDSIC-Icon-link||#||#||#||OxiADDSIC-SP-icon-color||#||#bd081c||#||OxiADDSIC-SP-H-icon-color||#||#ffffff||#||||#||||#||OxiADDSIC-SP-H-icon-bgcolor||#||rgba(189, 8, 28, 1)||#||OxiADDSIC-SP-border-color||#||#bd081c||#||OxiADDSIC-SP-H-border-color||#||#ff9ca6||#||||#|| ||#||##OXIDATA##',
);
if ($oxiimpport == 'import') {
    ?>
    <div class="wrap">
        <?php
        echo OxiAddonsAdmAdminMenu($oxitype, '', '', 'yes');
        echo '<div class="oxi-addons-wrapper">
                <div class="oxi-addons-row">
                    <div class="oxi-addons-view-more-demo" style=" padding-top: 35px; padding-bottom: 35px; ">
                        <div class="oxi-addons-view-more-demo-data" >
                            <div class="oxi-addons-view-more-demo-icon">
                                <i class="fas fa-bullhorn oxi-icons"></i>
                            </div>
                            <div class="oxi-addons-view-more-demo-text">
                                <div class="oxi-addons-view-more-demo-heading">
                                    More Layouts
                                </div>
                                <div class="oxi-addons-view-more-demo-content">
                                    Thank you for using Shortcode Addons. As limitation of viewing Layouts or Design we added some layouts. Kindly check more  <a target="_blank" href="https://www.oxilab.org/shortcode-addons-features/' . str_replace('_', '-', $oxitype) . '" >' . oxi_addons_shortcode_name_converter($oxitype) . '</a> design from Oxilab.org. Copy <strong>export</strong> code and <strong>import</strong> it, get your preferable layouts.
                                </div>
                            </div>
                            <div class="oxi-addons-view-more-demo-button">
                                <a target="_blank" class="oxi-addons-more-layouts" href="https://www.oxilab.org/shortcode-addons-features/' . str_replace('_', '-', $oxitype) . '" >View layouts</a>
                            </div>
                        </div>
                    </div>
                </div>
           </div>';
        ?>

        <div class="oxi-addons-wrapper">
            <div class="oxi-addons-row">
                <?php
                foreach ($file as $value) {
                    $expludedata = explode('OXIIMPORT', $value);
                    $datatrue = '';
                    foreach ($importstyle as $vals) {
                        if ($vals['name'] == $expludedata[2]) {
                            $datatrue = 'true';
                        }
                    }
                    if ($datatrue != 'true') {
                        $number = rand();
                        echo '<div class="oxi-addons-col-1"><div class="oxi-addons-style-preview"><div class="oxi-addons-style-preview-top oxi-addons-center">';
                        echo OxiDataAdminShortcode($oxitype, $value);
                        echo '</div>
                         <div class="oxi-addons-style-preview-bottom">
                            <div class="oxi-addons-style-preview-bottom-left">';
                        echo OxiDataAdminShortcodeName($value);
                        echo '       </div>';
                        echo '  <div class="oxi-addons-style-preview-bottom-right">
                                    <form method="post" style=" display: inline-block; ">
                                        ' . wp_nonce_field("oxi-addons-$expludedata[1]-style-active-nonce") . '
                                        <input type="hidden" name="oxiactivestyle" value="' . $expludedata[2] . '">
                                        <button class="btn btn-success" title="Active"  type="submit" value="Active" name="addonsstyleactive">Import Style</button>  
                                    </form> 
                                </div>';
                        echo '            </div>
                   </div>
                </div>';
                    }
                }
                ?>
            </div>
        </div>
    </div>

<?php
} else {
    $data = $wpdb->get_results("SELECT * FROM $table_name WHERE type = '$oxitype' ORDER BY id DESC", ARRAY_A);
    ?>
    <div class="wrap">
        <?php echo OxiAddonsAdmAdminMenu($oxitype, '', '', 'yes'); ?>
        <?php echo OxiAddonsAdmAdminShortcodeTable($data, $oxitype); ?>
        <div class="oxi-addons-wrapper">
            <div class="oxi-addons-row">
                <?php
                foreach ($file as $value) {
                    $expludedata = explode('OXIIMPORT', $value);
                    $datatrue = '';
                    foreach ($importstyle as $vals) {
                        if ($vals['name'] == $expludedata[2]) {
                            $datatrue = 'true';
                        }
                    }
                    if ($datatrue == 'true') {
                        $number = rand();
                        echo '<div class="oxi-addons-col-1" id="' . $expludedata[2] . '"><div class="oxi-addons-style-preview"><div class="oxi-addons-style-preview-top oxi-addons-center">';
                        echo OxiDataAdminShortcode($oxitype, $value);
                        echo '</div>
                         <div class="oxi-addons-style-preview-bottom">
                            <div class="oxi-addons-style-preview-bottom-left">';
                        echo OxiDataAdminShortcodeName($value);
                        echo '       </div>';
                        echo OxiDataAdminShortcodeControl($number, $value, $freeimport);
                        echo '            </div>
                   </div>
                </div>';
                    }
                }
                ?>
                <div class="oxi-addons-col-1 oxi-import">
                    <div class="oxi-addons-style-preview">
                        <div class="oxilab-admin-style-preview-top">
                            <a href="<?php echo admin_url("admin.php?page=oxi-addons&oxitype=$oxitype&oxiimpport=import"); ?>">
                                <div class="oxilab-admin-add-new-item">
                                    <span>
                                        <i class="fas fa-plus-circle oxi-icons"></i>
                                        Add More Templates
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php
    echo OxiDataAdminShortcodeModal($oxitype);
}








