<?php
if (!defined('ABSPATH'))
    exit;
$oxitype = sanitize_text_field($_GET['oxitype']);
oxi_addons_user_capabilities();
OxiDataAdminImport($oxitype);
global $wpdb;
$table_name = $wpdb->prefix . 'oxi_div_style';
$data = $wpdb->get_results("SELECT * FROM $table_name WHERE type = '$oxitype' ORDER BY id DESC", ARRAY_A);
?>
<div class="wrap">     
    <?php
    echo OxiAddonsAdmAdminMenu($oxitype, '', '', 'yes');
    echo OxiAddonsAdmAdminShortcodeTable($data, $oxitype);
    ?>
    <div class="oxi-addons-wrapper">
        <div class="oxi-addons-row">
            <?php
            $file = Array(
                'Style 1 Demo 1OXIIMPORTheadingOXIIMPORTstyle-1OXIIMPORToxi_addons-heading-text ||#||This is Heading||#||oxi_addons-heading-text-align |center|oxi-addons-heading-padding-top |10|15|10|oxi-addons-heading-padding-bottom |10|15|10|oxi-addons-heading-padding-left |10|15|10|oxi-addons-heading-padding-right |10|15|10| oxi_addons-heading-font-size |60|60|60| oxi_addons-heading-tag |h2| oxi_addons-heading-color |#252b25| oxi_addons-heading-family |Inherit| oxi_addons-heading-font-weight |600| oxi_addons-heading-font-style |initial| oxi_addons-heading-margin-top |10|5|5| oxi_addons-heading-margin-bottom |10|5|5| oxi-addons-heading-border|0|solid|#595959|oxi_addons-heading-animation|||2//|||||||||||||oxi-addons-preview-BG ||',
                'Style 1 Demo 2OXIIMPORTheadingOXIIMPORTstyle-1OXIIMPORToxi_addons-heading-text ||#||This is Heading||#||oxi_addons-heading-text-align |center|oxi-addons-heading-padding-top |10|15|10|oxi-addons-heading-padding-bottom |10|15|10|oxi-addons-heading-padding-left |10|15|10|oxi-addons-heading-padding-right |10|15|10| oxi_addons-heading-font-size |60|60|60| oxi_addons-heading-tag |h1| oxi_addons-heading-color |#2e2a2e| oxi_addons-heading-family |Alegreya+Sans+SC| oxi_addons-heading-font-weight |600| oxi_addons-heading-font-style |normal| oxi_addons-heading-margin-top |10|5|5| oxi_addons-heading-margin-bottom |10|5|5| oxi-addons-heading-border|3|solid|#292729|oxi_addons-heading-animation|swing|0.5|0.7//|||||||||||||oxi-addons-preview-BG ||',
                'Style 2OXIIMPORTheadingOXIIMPORTstyle-2OXIIMPORToxi_addons-heading-text ||#||Create a Heading Style||#||heading-image ||#||https://www.oxilab.org/wp-content/uploads/2019/04/180168-nature-landscape-animals-trees-sunset-silhouette-birds-photo_manipulation-deer-horizon-reflection-orange.jpg||#||oxi_addons-heading-text-align |center|oxi-addons-heading-padding-top |10|10|10|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |0|10|10|oxi-addons-heading-padding-right |10|10|10| oxi_addons-heading-font-size |60|60|60| oxi_addons-heading-tag |h1| || oxi_addons-heading-family |Adamina| oxi_addons-heading-font-weight |bold| oxi_addons-heading-font-style |normal| oxi_addons-heading-margin-top |5|5|5| oxi_addons-heading-margin-bottom |5|5|5| oxi-addons-heading-border|0|solid|#d600c4|oxi_addons-heading-animation|wobble||2//|||||||||||||oxi-addons-preview-BG ||',
                'Style 3OXIIMPORTheadingOXIIMPORTstyle-3OXIIMPORToxi_addons-heading-text ||#||This Is <span>Headings</span>||#||oxi_addons-heading-text-align |center|oxi-addons-heading-padding-top |10|10|10|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |10|10|10|oxi-addons-heading-padding-right |10|10|10| oxi_addons-heading-font-size |55|55|55| oxi_addons-heading-tag |h1| oxi_addons-heading-color |#595959| oxi_addons-heading-family |Open+Sans| oxi_addons-heading-font-weight |600| oxi_addons-heading-font-style |initial| oxi_addons-heading-margin-top |5|5|5| oxi_addons-heading-margin-bottom |10|5|5| oxi-addons-heading-border|2|solid|#595959|oxi_addons-heading-animation|||2//|oxi_addons-heading-span-color|#d4c711| oxi_addons-heading-span-family |sanfransisco| oxi_addons-heading-span-font-weight |600| oxi_addons-heading-span-font-style |normal|||||oxi-addons-preview-BG ||',
                'Style 4OXIIMPORTheadingOXIIMPORTstyle-4OXIIMPORT||||||||||||||||||||||||||||||||||oxi_addons-heading-font-size|50|50|50| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#6fab30|oxi-addons-heading-font-S-family |Actor|100|oxi-addons-heading-font-S-style |normal:1.3|center:1.3()()()|oxi-addons-heading-padding-top |0|10|10|oxi-addons-heading-padding-bottom |0|10|10|oxi-addons-heading-padding-left |0|10|10|oxi-addons-heading-padding-right |0|10|10|oxi_addons-content-font-size|20|20|20|||oxi_addons-content-color|#3d3d3d|oxi-addons-content-font-S-family |Amiri|100|oxi-addons-content-font-S-style |normal:1.3|center:1.3()()()|oxi-addons-content-padding-top |0|0|0|oxi-addons-content-padding-bottom |0|0|0|oxi-addons-content-padding-left |0|0|0|oxi-addons-content-padding-right |0|0|0|oxi_addons-heading-animation|||1//|oxi-addons-preview-BG ||||||||||||||||||#||||#||oxi_addons-heading-text ||#||Elementor Builder||#||xi_addons-content-text ||#||Lorem ipsum dolor sit amet, consectetur adipisicin elit sed. For example, helper text on light backgrounds could apply the following opacity levels and default hexes:||#|||',
                'Style 5OXIIMPORTheadingOXIIMPORTstyle-5OXIIMPORToxi-addons-preview-BG ||oxi_addons-heading-font-size|50|30|20|oxi_addons-heading-color|#000000| oxi_addons-heading-tag |h1| oxi_addons-heading-BG-color|rgba(118, 240, 142, 0.34)|oxi-addons-heading-font-S-family |Aldrich|100|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-border-C-S |solid|#3eb39c||oxi-addons-heading-margin-top |0|0|0|oxi-addons-heading-margin-bottom |0|0|0|oxi-addons-heading-margin-left |0|0|0|oxi-addons-heading-margin-right |0|0|0|oxi-addons-heading-padding-top |10|10|10|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |20|20|20|oxi-addons-heading-padding-right |20|20|20|oxi_addons-content-font-size|22|22|22|oxi_addons-content-color|#000000|oxi-addons-content-font-S-family |Abel|100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-content-padding-top |10|10|10|oxi-addons-content-padding-bottom |0|0|0|oxi-addons-content-padding-left |0|0|0|oxi-addons-content-padding-right |0|0|0|oxi_addons-heading-animation||0|0//|oxi-addons-heading-border-height |5|5|5|||||oxi-addons-main-border-width |5|5|5| oxi_addons-heading-border-color|rgba(124, 235, 147, 1)|||||||||||||||||#||||#||oxi_addons-heading-text ||#||Middle Align Heading||#||xi_addons-content-text ||#||Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ut blandit tortor. Nam ac sodales lectus. Donec tincidunt magna lorem||#|||',
                'Style 6OXIIMPORTheadingOXIIMPORTstyle-6OXIIMPORT||||||||||||||||||||||||||||||||||oxi_addons-heading-font-size|50|40|35| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#000000|oxi-addons-heading-font-S-family ||100|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-heading-padding-top |10|10|10|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |10|10|10|oxi-addons-heading-padding-right |10|10|10|oxi_addons-content-font-size|22|18|15|||oxi_addons-content-color|#000000|oxi-addons-content-font-S-family ||100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-content-padding-top |10|10|10|oxi-addons-content-padding-bottom |10|10|10|oxi-addons-content-padding-left |10|10|10|oxi-addons-content-padding-right |10|10|10|oxi_addons-heading-animation|pulse|1|0.2//|oxi-addons-bg-img-padding-top |0|0|0|oxi-addons-bg-img-padding-bottom |0|0|0|oxi-addons-bg-img-padding-left |0|0|0|oxi-addons-bg-img-padding-right |0|0|0|oxi-addons-preview-BG ||||||||||||||||||#||||#||oxi_addons-heading-text ||#||Middle <span style="color:#902712;"> Align </span> Heading||#||oxi_addons-content-text ||#||SUB TITLE HERE||#||oxi-add-bg-img ||#||https://www.oxilab.org/wp-content/uploads/2019/03/maxresdefault-1.jpg||#|||',
                'Style 7OXIIMPORTheadingOXIIMPORTstyle-7OXIIMPORT||oxi-addons-G-padding-top |0|0|0|oxi-addons-G-padding-bottom |0|0|0|oxi-addons-G-padding-left |0|0|0|oxi-addons-G-padding-right |0|0|0|oxi_addons-G-margin-top |0|0|0|oxi_addons-G-margin-bottom |0|0|0|oxi_addons-G-margin-left |0|0|0|oxi_addons-G-margin-right |0|0|0|oxi_addons-heading-font-size|50|40|35| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#000000|oxi-addons-heading-font-S-family |Amiko|100|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-heading-padding-top |0|0|0|oxi-addons-heading-padding-bottom |0|0|0|oxi-addons-heading-padding-left |0|0|0|oxi-addons-heading-padding-right |0|0|0|oxi_addons-content-font-size|22|18|15|||oxi_addons-content-color|#000000|oxi-addons-content-font-S-family |Advent+Pro|bold|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-content-padding-top |10|10|10|oxi-addons-content-padding-bottom |10|10|10|oxi-addons-content-padding-left |10|10|10|oxi-addons-content-padding-right |10|10|10|oxi_addons-heading-animation|||//|oxi-addons-bg-img-padding-top |-40|-40|-40|oxi-addons-bg-img-padding-bottom |-45|-45|-45|oxi-addons-bg-img-padding-left |0|0|0|oxi-addons-bg-img-padding-right |0|0|0|oxi-addons-preview-BG ||oxi-addons-image-align|center|oxi-addons-img-width |400|100|80|oxi-addons-img-height |100|80|100|oxi-addons-bg-img-position |2|||||||#||||#||oxi_addons-heading-text ||#||Middle Align Heading||#||oxi_addons-content-text ||#||SUB TITLE HERE||#||oxi-add-bg-img ||#||https://www.oxilab.org/wp-content/uploads/2019/03/divider-2461548__340.png||#|||',
                'Style 8 testOXIIMPORTheadingOXIIMPORTstyle-8OXIIMPORT||||||||||||||||||||||||||||||||||oxi_addons-heading-font-size|50|40|35| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#000000|oxi-addons-heading-font-S-family |Belleza|100|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff:|oxi-addons-heading-padding-top |0|0|0|oxi-addons-heading-padding-bottom |0|0|0|oxi-addons-heading-padding-left |0|0|0|oxi-addons-heading-padding-right |0|0|0|oxi_addons-content-font-size|22|20|15|||oxi_addons-content-color|#4d4d4d|oxi-addons-content-font-S-family |Inherit|100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff:|oxi-addons-content-padding-top |0|0|0|oxi-addons-content-padding-bottom |0|0|0|oxi-addons-content-padding-left |0|0|0|oxi-addons-content-padding-right |0|0|0|oxi_addons-heading-animation||1|1//|oxi-addons-preview-BG ||oxi_addons-watermark-font-size|115|80|50|||oxi_addons-watermark-color |rgba(50, 132, 153, 0.2)|oxi-addons-watermark-font-S-family |Open+Sans+Condensed:300|600|oxi-addons-watermark-font-S-style |normal:1.3|center:0()0()2()#ffffff:|oxi-addons-watermark-padding-top |41|41|41|oxi-addons-watermark-padding-bottom |0|0|0|oxi-addons-watermark-padding-left |0|0|0|oxi-addons-watermark-padding-right |0|0|0|||||||||||||||||#||||#||oxi_addons-heading-text ||#||Elementor Align Heading||#||xi_addons-content-text ||#||SUB TITLE HERE||#||xi_addons-watermark-text ||#||Elementor||#|||',
                'Style 9OXIIMPORTheadingOXIIMPORTstyle-9OXIIMPORT||||||||||||||||||||||||||||||||||oxi_addons-heading-font-size|50|40|35| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#1f0c0c|oxi-addons-heading-font-S-family |Nunito|100|oxi-addons-heading-font-S-style |normal:1.3|left:0()0()2()#ffffff|oxi-addons-heading-padding-top |10|10|10|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |10|10|10|oxi-addons-heading-padding-right |10|10|10|oxi_addons-content-font-size|22|20|15|||oxi_addons-content-color|#4d4d4d|oxi-addons-content-font-S-family |Abel|100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-content-padding-top |0|0|0|oxi-addons-content-padding-bottom |0|0|0|oxi-addons-content-padding-left |0|0|0|oxi-addons-content-padding-right |0|0|0|oxi_addons-heading-animation||1|.5//|oxi-addons-preview-BG ||||||oxi-addons-heading-line-color|rgba(212, 55, 55, 1)|oxi-addons-heading-line-width |100|50|30|oxi-addons-heading-line-height |3|3|3|||||||||||||||||#||||#||oxi_addons-heading-text ||#||Middle Align Heading||#||oxi_addons-content-text ||#||SUBTITLE||#|||',
                'Style 10OXIIMPORTheadingOXIIMPORTstyle-10OXIIMPORT||||||||||||||||||oxi_addons-line-margin-top |0|0|0|oxi_addons-line-margin-bottom |0|0|0|oxi_addons-line-margin-left |0|0|0|oxi_addons-line-margin-right |0|0|0|oxi_addons-heading-font-size|50|40|35| oxi_addons-heading-tag |h1|oxi_addons-heading-color|#000000|oxi-addons-heading-font-S-family |Belleza|100|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-heading-padding-top |0|0|0|oxi-addons-heading-padding-bottom |0|0|0|oxi-addons-heading-padding-left |10|10|10|oxi-addons-heading-padding-right |10|10|10|oxi_addons-content-font-size|22|20|15|||oxi_addons-content-color|#4d4d4d|oxi-addons-content-font-S-family |Inherit|100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-content-padding-top |0|0|0|oxi-addons-content-padding-bottom |0|0|0|oxi-addons-content-padding-left |10|10|10|oxi-addons-content-padding-right |10|10|10|oxi_addons-heading-animation||1|1//|oxi-addons-preview-BG |rgba(252, 252, 252, 1)|oxi-addons-heading-line-color |rgba(135, 135, 135, 1)|oxi-addons-heading-line-width |130|oxi-addons-heading-line-height|3|oxi-addons-line-position|3|||||||||||||||||#||||#||oxi_addons-heading-text ||#||Daily Design Showcase||#||xi_addons-content-text ||#||Lorem ipsum||#|||',
                'Style 11OXIIMPORTheadingOXIIMPORTstyle-11OXIIMPORToxi-addons-preview-BG |rgba(219, 219, 219, 0.39)|oxi_addons-heading-font-size|50|30|25|oxi_addons-heading-color|#000000| oxi_addons-heading-tag |h4| oxi_addons-heading-BG-color|rgba(60, 217, 123, 1)|oxi-addons-heading-font-S-family |ABeeZee|500|oxi-addons-heading-font-S-style |normal:1.3|center:0()0()2()#ffffff|oxi-addons-border-C-S |solid|#34c76a||oxi-addons-border-width |2|2|2|||||||||||||oxi-addons-heading-padding-top |0|0|0|oxi-addons-heading-padding-bottom |10|10|10|oxi-addons-heading-padding-left |10|10|10|oxi-addons-heading-padding-right |20|20|20|oxi_addons-content-font-size|20|20|20|oxi_addons-content-color|#1c1c1c|oxi-addons-content-font-S-family |18|100|oxi-addons-content-font-S-style |normal:1.3|center:0()0()0()#ffffff|oxi-addons-content-padding-top |0|0|0|oxi-addons-content-padding-bottom |10|10|10|oxi-addons-content-padding-left |0|0|0|oxi-addons-content-padding-right |0|0|0|oxi_addons-heading-animation||0|0//|||||||||||||||||#||||#||oxi_addons-heading-text ||#||Heading||#||xi_addons-content-text ||#||Lorem ipsum dolor sit amet, consectetur adipisicin elit sed.Lorem ipsum dolor sit amet, consectetur adipisicin elit sed.Lorem ipsum dolor sit amet, consectetur adipisicin elit sed.||#|||',



            );
            foreach ($file as $value) {
                $number = rand();
                echo '<div class="oxi-addons-col-1"><div class="oxi-addons-style-preview"><div class="oxi-addons-style-preview-top oxi-addons-center">';
                echo OxiDataAdminShortcode($oxitype, $value);
                echo '</div>
                         <div class="oxi-addons-style-preview-bottom">
                            <div class="oxi-addons-style-preview-bottom-left">';
                echo OxiDataAdminShortcodeName($value);
                echo '            </div>';
                echo OxiDataAdminShortcodeControl($number, $value, array('style-1','style-2','style-3','style-4'));
                echo '        </div>
                     </div>
                     </div>';
            }
            ?>
        </div>
    </div>
</div>

<?php
echo OxiDataAdminShortcodeModal($oxitype);
