

<?php
if (!defined('ABSPATH')) {
    exit;
}

$oxitype = sanitize_text_field($_GET['oxitype']);
$oxiimpport = '';
if (!empty($_GET['oxiimpport'])) {
    $oxiimpport = sanitize_text_field($_GET['oxiimpport']);
}

oxi_addons_user_capabilities();
OxiDataAdminImport($oxitype);
global $wpdb;
$table_name = $wpdb->prefix . 'oxi_div_style';
$table_import = $wpdb->prefix . 'oxi_div_import';
$importstyle = $wpdb->get_results("SELECT * FROM $table_import WHERE type = '$oxitype' ORDER BY id DESC", ARRAY_A);
$freeimport = array('style-1', 'style-2', 'style-3', 'style-4');
if (count($importstyle) < 1) {
    foreach ($freeimport as $value) {
        $wpdb->query($wpdb->prepare("INSERT INTO {$table_import} (type, name) VALUES (%s, %s )", array($oxitype, $value)));
    }
    $js = 'location.reload();';
    wp_add_inline_script('oxi-addons-vendor', $js);
}

$file = Array(
    'Style 1OXIIMPORTbutton_effectsOXIIMPORTstyle-1OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(238, 30, 245, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(238, 30, 245, 0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#ee1ef5| OxiAdmin-button-bgcolor |rgba(255,255,255,1.00)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(241,30,245,1.00)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/17022134_1860060914281239_3308140103608683490_n-e1557129013425.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 2 <span> 4 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-2OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(3, 222, 196, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(3,222,196,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#03dec4| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(3,222,196,1.00)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-top-to-bottom|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/download.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 3 <span> 2 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-3OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(10, 235, 247, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(10,235,247,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#0aebf7| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(10,231,247,1.00)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-left-to-right|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/jewelry-on-black-background-6-e1556940516674.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 4 <span> 2 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-4OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(222, 120, 3, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(222,120,3,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#de7803| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(222,123,3,1.00)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-right-to-left|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/59754353_1506074499529056_9010189672965472256_n-e1557129031866.png||#||||#|| ||#||##OXIDATA##',
    'Style 5 <span> 3 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-5OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(3, 222, 178, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(3,222,178,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#03deb2| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(3,222,178,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-right-to-left|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/1.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 6 <span> 4 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-6OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(189, 0, 0, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|180|OxiAdmin-I-bg|rgba(112,3,222,0.00)|https://www.oxilab.org/wp-content/uploads/2019/05/creative-watches-12-e1557200454951.jpg||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#bd0000| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(189,0,0,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-top-to-bottom|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/3.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 7 <span> 2 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-7OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(109, 3, 222, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|200|OxiAdmin-I-bg|rgba(112,3,222,0.00)|https://www.oxilab.org/wp-content/uploads/2019/05/nurserylive-fruit-plant-pairi-pairi-mango.jpg||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#9100bd| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(145, 0, 189, 0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-right-to-left|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/bloom-blossom-dew-56866.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 8 <span> 2 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-8OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(240, 12, 194, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|200|OxiAdmin-I-bg|rgba(240,12,194,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#f00cc2| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(240,12,194,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-right-to-left|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/bloom-blossom-dahlia-60597.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 9 <span> 2 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-9OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(8, 204, 191, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|200|OxiAdmin-I-bg|rgba(8,204,191,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#08ccbf| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(8,204,191,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-left-to-right|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/5.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 10 <span> 4 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-10OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(3, 193, 222, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|200|OxiAdmin-I-bg|rgba(3,193,222,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#03c1de| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(3,193,222,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-left-to-right|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/2-1.jpg||#||||#|| ||#||##OXIDATA##',
    'Style 11 <span> 4 effects</span>OXIIMPORTbutton_effectsOXIIMPORTstyle-11OXIIMPORToxi-addons-preview-BG || ||image-alignments|justify-content: center; align-items: center;|OxiAdmin-Item |oxi-addons-lg-col-1|oxi-addons-md-col-1|oxi-addons-xs-col-1| OxiAddCB-button-link-opening ||OxiAdmin-padding-top |20|20|20|OxiAdmin-padding-bottom |20|20|20|OxiAdmin-padding-left |20|20|20|OxiAdmin-padding-right |20|20|20|OxiAdmin-margin-top |3|3|3|OxiAdmin-margin-bottom |3|3|3|OxiAdmin-margin-left |3|3|3|OxiAdmin-margin-right |3|3|3|OxiAdmin-animation||2:false:false:500:10:0.2|0//|OxiAdmin-box-shadow |rgba(224, 224, 224, 0.74)|0|0|3|1||OxiAdmin-hover-box-shadow |rgba(153, 3, 222, 0.49)|0|0|3|1|| OxiAdmin-width |250| OxiAdmin-height|200|OxiAdmin-I-bg|rgba(153,3,222,0.49)|||OxiAdmin-border-radius-top |0|0|0|OxiAdmin-border-radius-bottom |0|0|0|OxiAdmin-border-radius-left |0|0|0|OxiAdmin-border-radius-right |0|0|0|OxiAdmin-hover-border-radius-top |0|0|0|OxiAdmin-hover-border-radius-bottom |0|0|0|OxiAdmin-hover-border-radius-left |0|0|0|OxiAdmin-hover-border-radius-right |0|0|0|OxiAdmin-button-size |18|18|18|OxiAdmin-button-width-height |40|40|40| OxiAdmin-button-color |#9903de| OxiAdmin-button-bgcolor |rgba(255, 255, 255, 1)|OxiAdmin-button-border-top |0|0|0|OxiAdmin-button-border-bottom |0|0|0|OxiAdmin-button-border-left |0|0|0|OxiAdmin-button-border-right |0|0|0|OxiAdmin-button-border |solid|#ffffff||OxiAdmin-button-radius-top |50|50|50|OxiAdmin-button-radius-bottom |50|50|50|OxiAdmin-button-radius-left |50|50|50|OxiAdmin-button-radius-right |50|50|50|OxiAdmin-button-margin-top |3|3|3|OxiAdmin-button-margin-bottom |3|3|3|OxiAdmin-button-margin-left |3|3|3|OxiAdmin-button-margin-right |3|3|3| OxiAdmin-button-hover-color |#ffffff| OxiAdmin-button-hover-bgcolor |rgba(153,3,222,0.81)|OxiAdmin-hover-button-border |solid|#ffffff||OxiAdmin-hover-button-radius-top |50|50|50|OxiAdmin-hover-button-radius-bottom |50|50|50|OxiAdmin-hover-button-radius-left |50|50|50|OxiAdmin-hover-button-radius-right |50|50|50|effects-alignments |oxi-button-top-to-bottom|||#|| ||#|||##OXISTYLE##OxiAdmin-file-first-icon||#||fas fa-search-plus||#||OxiAdmin-file-first-link||#||#||#||OxiAdmin-file-second-icon||#||fab fa-facebook||#||OxiAdmin-file-second-link||#||#||#||OxiAdmin-file-image||#||https://www.oxilab.org/wp-content/uploads/2019/05/4.jpg||#||||#|| ||#||##OXIDATA##',
);
if ($oxiimpport == 'import') {
    ?>
    <div class="wrap">
        <?php
        echo OxiAddonsAdmAdminMenu($oxitype, '', '', 'yes');
        echo '<div class="oxi-addons-wrapper">
                <div class="oxi-addons-row">
                    <div class="oxi-addons-view-more-demo" style=" padding-top: 35px; padding-bottom: 35px; ">
                        <div class="oxi-addons-view-more-demo-data" >
                            <div class="oxi-addons-view-more-demo-icon">
                                <i class="fas fa-bullhorn oxi-icons"></i>
                            </div>
                            <div class="oxi-addons-view-more-demo-text">
                                <div class="oxi-addons-view-more-demo-heading">
                                    More Layouts
                                </div>
                                <div class="oxi-addons-view-more-demo-content">
                                    Thank you for using Shortcode Addons. As limitation of viewing Layouts or Design we added some layouts. Kindly check more  <a target="_blank" href="https://www.oxilab.org/shortcode-addons-features/' . str_replace('_', '-', $oxitype) . '" >' . oxi_addons_shortcode_name_converter($oxitype) . '</a> design from Oxilab.org. Copy <strong>export</strong> code and <strong>import</strong> it, get your preferable layouts.
                                </div>
                            </div>
                            <div class="oxi-addons-view-more-demo-button">
                                <a target="_blank" class="oxi-addons-more-layouts" href="https://www.oxilab.org/shortcode-addons-features/' . str_replace('_', '-', $oxitype) . '" >View layouts</a>
                            </div>
                        </div>
                    </div>
                </div>
           </div>';
        ?>

        <div class="oxi-addons-wrapper">
            <div class="oxi-addons-row">
                <?php
                foreach ($file as $value) {
                    $expludedata = explode('OXIIMPORT', $value);
                    $datatrue = '';
                    foreach ($importstyle as $vals) {
                        if ($vals['name'] == $expludedata[2]) {
                            $datatrue = 'true';
                        }
                    }
                    if ($datatrue != 'true') {
                        $number = rand();
                        echo '<div class="oxi-addons-col-6"><div class="oxi-addons-style-preview"><div class="oxi-addons-style-preview-top oxi-addons-center">';
                        echo OxiDataAdminShortcode($oxitype, $value);
                        echo '</div>
                         <div class="oxi-addons-style-preview-bottom">
                            <div class="oxi-addons-style-preview-bottom-left">';
                        echo OxiDataAdminShortcodeName($value);
                        echo '       </div>';
                        echo '  <div class="oxi-addons-style-preview-bottom-right">
                                    <form method="post" style=" display: inline-block; ">
                                        ' . wp_nonce_field("oxi-addons-$expludedata[1]-style-active-nonce") . '
                                        <input type="hidden" name="oxiactivestyle" value="' . $expludedata[2] . '">
                                        <button class="btn btn-success" title="Active"  type="submit" value="Active" name="addonsstyleactive">Import Style</button>  
                                    </form> 
                                </div>';
                        echo '            </div>
                   </div>
                </div>';
                    }
                }
                ?>
            </div>
        </div>
    </div>

    <?php
} else {
    $data = $wpdb->get_results("SELECT * FROM $table_name WHERE type = '$oxitype' ORDER BY id DESC", ARRAY_A);
    ?>
    <div class="wrap">
        <?php echo OxiAddonsAdmAdminMenu($oxitype, '', '', 'yes'); ?>
        <?php echo OxiAddonsAdmAdminShortcodeTable($data, $oxitype); ?>
        <div class="oxi-addons-wrapper">
            <div class="oxi-addons-row">
                <?php
                foreach ($file as $value) {
                    $expludedata = explode('OXIIMPORT', $value);
                    $datatrue = '';
                    foreach ($importstyle as $vals) {
                        if ($vals['name'] == $expludedata[2]) {
                            $datatrue = 'true';
                        }
                    }
                    if ($datatrue == 'true') {
                        $number = rand();
                        echo '<div class="oxi-addons-col-6" id="' . $expludedata[2] . '"><div class="oxi-addons-style-preview"><div class="oxi-addons-style-preview-top oxi-addons-center">';
                        echo OxiDataAdminShortcode($oxitype, $value);
                        echo '</div>
                         <div class="oxi-addons-style-preview-bottom">
                            <div class="oxi-addons-style-preview-bottom-left">';
                        echo OxiDataAdminShortcodeName($value);
                        echo '       </div>';
                        echo OxiDataAdminShortcodeControl($number, $value, $freeimport);
                        echo '            </div>
                   </div>
                </div>';
                    }
                }
                ?>
                <div class="oxi-addons-col-1 oxi-import">
                    <div class="oxi-addons-style-preview">
                        <div class="oxilab-admin-style-preview-top">
                            <a href="<?php echo admin_url("admin.php?page=oxi-addons&oxitype=$oxitype&oxiimpport=import"); ?>">
                                <div class="oxilab-admin-add-new-item">
                                    <span>
                                        <i class="fas fa-plus-circle oxi-icons"></i>  
                                        Add More Templates
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php
    echo OxiDataAdminShortcodeModal($oxitype);
}